name: baby_journal
description: add and share your baby memories with your family
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  qlevar_router: ^1.6.3
  get_it: ^7.2.0
  reactable: ^0.1.0
  lottie: ^1.4.2
  intl: ^0.17.0
  overlayment: ^0.1.1
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  age_calculator: ^1.0.0
  uuid: ^3.0.6
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  infinite_scroll_pagination: ^3.2.0
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21